services:
  wazuh-manager:
    image: wazuh/wazuh-manager:4.7.3
    container_name: wazuh-manager
    hostname: wazuh-manager
    network_mode: bridge
    restart: always
    depends_on:
      - wazuh-indexer
    links:
      - wazuh-indexer
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 655360
        hard: 655360
    ports:
    #  - "1514:1514"
    #  - "1515:1515"
    #  - "514:514/udp"
      - "55000:55000"
    environment:
      - INDEXER_URL=http://wazuh-indexer:9200
      - INDEXER_USERNAME=admin
      - INDEXER_PASSWORD=SecretPassword
      - FILEBEAT_SSL_VERIFICATION_MODE=none
      #- SSL_CERTIFICATE_AUTHORITIES=/etc/ssl/root-ca.pem
      #- SSL_CERTIFICATE=/etc/ssl/filebeat.pem
      #- SSL_KEY=/etc/ssl/filebeat.key
      - API_USERNAME=wazuh-wui
      - API_PASSWORD=ChangeMe
    volumes:
      - api_config:/var/ossec/api/configuration
      - config:/var/ossec/etc
      - logs:/var/ossec/logs
      - queue:/var/ossec/queue
      - multigroups:/var/ossec/var/multigroups
      - integrations:/var/ossec/integrations
      - active_response:/var/ossec/active-response/bin
      - agentless:/var/ossec/agentless
      - wodles:/var/ossec/wodles
      - filebeat_config:/etc/filebeat
      - filebeat_data:/var/lib/filebeat
      #- ./config/certs/root-ca.pem:/etc/ssl/root-ca.pem
      #- ./config/certs/wazuh.manager.pem:/etc/ssl/filebeat.pem
      #- ./config/certs/wazuh.manager-key.pem:/etc/ssl/filebeat.key
      - ./config/manager/api.yaml:/var/ossec/api/configuration/api.yaml
      - ./config/manager/ossec.conf:/wazuh-config-mount/etc/ossec.conf

  wazuh-indexer:
    image: wazuh/wazuh-indexer:4.7.3
    hostname: wazuh-indexer
    container_name: wazuh-indexer
    restart: always
    network_mode: bridge
    ports:
      - "9200:9200"
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - indexer_data:/var/lib/wazuh-indexer
      #- ./config/certs/root-ca.pem:/usr/share/wazuh-indexer/certs/root-ca.pem
      #- ./config/certs/wazuh.key:/usr/share/wazuh-indexer/certs/wazuh-indexer.key
      #- ./config/certs/wazuh.pem:/usr/share/wazuh-indexer/certs/wazuh-indexer.pem
      #- ./config/certs/admin.pem:/usr/share/wazuh-indexer/certs/admin.pem
      #- ./config/certs/admin-key.pem:/usr/share/wazuh-indexer/certs/admin-key.pem
      - ./config/indexer/opensearch.yml:/usr/share/wazuh-indexer/opensearch.yml
      - ./config/indexer/internal_users.yml:/usr/share/wazuh-indexer/opensearch-security/internal_users.yml

  wazuh-dashboard:
    image: wazuh/wazuh-dashboard:4.7.3
    hostname: wazuh-dashboard
    container_name: wazuh-dashboard
    restart: always
    network_mode: bridge
    ports:
      - 443:5601
    environment:
      - INDEXER_USERNAME=admin
      - INDEXER_PASSWORD=SecretPassword
      - WAZUH_API_URL=http://wazuh-manager
      - DASHBOARD_USERNAME=kibanaserver
      - DASHBOARD_PASSWORD=kibanaserver
      - API_USERNAME=wazuh-wui
      - API_PASSWORD=ChangeMe
    volumes:
      - dashboard_config:/usr/share/wazuh-dashboard/data/wazuh/config
      - dashboard_custom:/usr/share/wazuh-dashboard/plugins/wazuh/public/assets/custom
      #- ./config/certs/root-ca.pem:/usr/share/wazuh-dashboard/certs/root-ca.pem
      #- ./config/certs/wazuh.pem:/usr/share/wazuh-dashboard/certs/wazuh-dashboard.pem
      #- ./config/certs/wazuh.key:/usr/share/wazuh-dashboard/certs/wazuh-dashboard.key
      - ./config/dashboard/wazuh.yml:/usr/share/wazuh-dashboard/data/wazuh/config/wazuh.yml
      - ./config/dashboard/opensearch_dashboards.yml:/usr/share/wazuh-dashboard/config/opensearch_dashboards.yml
    depends_on:
      - wazuh-indexer
    links:
      - wazuh-indexer
      - wazuh-manager

volumes:
  api_config:
  config:
  logs:
  queue:
  multigroups:
  integrations:
  active_response:
  agentless:
  wodles:
  filebeat_config:
  filebeat_data:
  indexer_data:
  dashboard_config:
  dashboard_custom:
